---
- hosts:
  - OSEv3
  tasks:
  - name: Check for FQDN variable presence
    fail:
      msg: "FQDN variable is not set!"
    when: fqdn|default(False) == False


  - name: Check for hostname variable presence
    fail:
      msg: "Hostname variable is not set!"
    when: fqdn|default(False) == False


  - hostname: name={{ fqdn }}


  - name: Re-gather facts
    action: setup
    when: inventory_hostname != fqdn


  # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
  # Will include all hosts the playbook is run on.
  # Credits to rothgar: https://gist.github.com/rothgar/8793800
  - name: Build hosts file (backups will be made)
    lineinfile: >
      dest=/etc/hosts 
      regexp='{{ hostvars[item].ansible_hostname }}$' 
      line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ hostvars[item].ansible_hostname }}' 
      state=present 
      backup=yes
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']