apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: gluster-block
provisioner: gluster.org/glusterblock
parameters:
 resturl: "http://heketi-storage.glusterfs.svc:8080"
 restuser: "admin"
 secretNamespace: "glusterfs"
 secretName: "heketi-storage-admin-secret"
 hacount: "3"
